# Site settings
author: Saida Davis
title: Why did you decide to study Software Engineering?
header-img: img/home-bg.png
email: saihdavis@gmail.com
copyright_name: Saida Davis
description: > # this means to ignore newlines until "baseurl:"
  Goal
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  saihdavis

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
